### ISSUE TITLE
duplicate PropertySourcesPlaceholderConfigurer causes placeholders not working anymore

### ISSUE THREAD

**Issue by BigMichi1** [cibseven/cibseven#85]
### Environment (Required on creation)

cib seven 2.0.0

### Description (Required on creation; please attach any relevant screenshots, stacktraces, log files, etc. to the ticket)

`SevenWebclientContext` adds a Bean of type `PropertySourcesPlaceholderConfigurer` with bean name `placeholderConfigurer`. Spring-Boot does the same in `PropertyPlaceholderAutoConfiguration` but with a different name `propertySourcesPlaceholderConfigurer` this results in two beans defined with same type but different names and fails in `PropertySourcesDeducer`. Result is that no placeholders are working because when more than one bean is found null is returned in spring boot

### Observed Behavior (Required on creation)

Two beans of type `PropertySourcesPlaceholderConfigurer` are defined

### Expected behavior (Required on creation)

only one bean of type `PropertySourcesPlaceholderConfigurer` should be defined

### Solution Ideas

- adding `@Primary` to bean definition in `SevenWebclientContext`
- do not define it at all (Spring boot does it anyay)
- add some Guard to bean definition in `SevenWebclientContext` like `@ConditionalOnMissingBean`

### Breakdown

```[tasklist]
### Pull Requests
```

**Comment by OlegCIB** [comment]
Hello Michael,

thank you for bringing this issue to our attention.

We will try to remove the bean definition on our side and then retest to see if this solution works for all distributions.

Could you please tell us more about your setup? For example, which CIB seven dependency are you using in your project?
Do you also need to define the same bean in your code?

We have not encountered such problems in the [starter](https://github.com/cibseven/cibseven/blob/v2.0.0/spring-boot-starter/starter/pom.xml#L29) project that is used in the [CIB seven Run](https://cibseven.org/download/#run) distribution.

As a temporary workaround until we resolve this issue, could you try adding the `@Primary` annotation to your bean definition?

Cheers,
Oleg

**Comment by BigMichi1** [comment]
in general we use spring-boot 3.4.5 with cib seven 2.0.0 and swagger 2.2.30

we are not defining this bean in our code, according to docs this bean is defined since version 1.5.0 by spring-boot autoconfiguration

my `libs.version.toml` contains:

```toml
[versions]
sibseven = "2.0.0"
sibseven-rest = "1.1.0"
swagger = "2.2.30"

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.4.5" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }

[libraries]
sibseven-starter = { module = "org.cibseven.bpm.springboot:cibseven-bpm-spring-boot-starter", version.ref = "sibseven" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
sibseven-spin-dataformat = { module = "org.cibseven.spin:cibseven-spin-dataformat-all", version.ref = "sibseven" }
sibseven-spin-engine-plugin = { module = "org.cibseven.bpm:cibseven-engine-plugin-spin", version.ref = "sibseven" }
sibseven-starter-test = { module = "org.cibseven.bpm.springboot:cibseven-bpm-spring-boot-starter-test", version.ref = "sibseven" }
sibseven-starter-webapp = { module = "org.cibseven.bpm.springboot:cibseven-bpm-spring-boot-starter-webapp", version.ref = "sibseven" }
sibseven-engine-rest-openapi = { module = "org.cibseven.bpm:cibseven-engine-rest-openapi", version.ref = "sibseven-rest" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger" }

[bundles]
sibseven-full = ["sibseven-starter", "spring-boot-starter-jdbc", "spring-boot-starter-actuator", "spring-boot-starter-validation", "spring-boot-starter-web", "sibseven-spin-dataformat", "sibseven-spin-engine-plugin", "sibseven-starter-rest", "sibseven-starter-webapp", "sibseven-engine-rest-openapi", "swagger-annotations"]
```

and `build.gradle.kts`

```kotlin
plugins {
  alias(libs.plugins.spring.boot)
  alias(libs.plugins.spring.dependency.management)
}

dependencies {
  implementation(project(":bpmn2-generator"))

  runtimeOnly(libs.h2)
}
```
